=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Einflusfaktoren und Randbedingungen dokumentieren 

Softwarearchitekt:innen können Faktoren, die Einfluss auf Softwarearchitektur haben, identifizieren und geeignet dokumentieren.
Dazu zählen:

* Randbedingungen 
* Qualitätsanforderungen und -ziele
* Technische Risiken

[[LZ-3-2]]
==== LZ 3-2: Architekturentscheidungen dokumentieren

Softwarearchitekt:innen können Architekturentscheidungen nachvollziehbar festhalten.
Sie kennen beispielsweise _Architecture Decision Records_ als eine feste Struktur für solche Entscheidungen.



[[LZ-3-3]]
==== LZ 3-3: Architektursichten dokumentieren

Softwarearchitekt:innen können

[[LZ-3-4]]
==== LZ 3-4: Übergreifende Konzepte dokumentieren

Softwarearchitekt:innen können

[[LZ-3-5]]
==== LZ 3-5: Konsistenz zwischen Teilen der Dokumentation sicherstellen

Softwarearchitekt:innen können



// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 1-1:
tbd.
// end::EN[]

// tag::REMARK[]
aus V 1.5

Was sollen die Teilnehmer können?
Die Architektur mittlerer bis großer IT-Systeme selbständig dokumentieren, sowohl entwicklungsbegleitend, wie bei Bedarf auch a posteriori („Nachdokumentation“).
Vorhandene Architekturdokumentation weiterentwickeln und pflegen, dabei die Qualität der Dokumentation systematisch verbessern.
Für mittlere bis große Systeme spezifisch geeignete Arten und Strukturen der Architekturdokumentation erarbeiten oder auswählen.
Faktoren, die Einfluss auf Software-Architektur haben, identifizieren und geeignet dokumentieren, z. B.
o Randbedingungen o Qualitätsziele
o Technische Risiken
Architekturentscheidungen nachvollziehbar festhalten
Unterschiedliche Sichten auf Software-Architektur mit geeigneten Beschreibungsmitteln anfertigen
o Verschiedene Aspekte von Bausteinsichten erklären und dokumentieren (Darstellung als hierarchische Verfeinerung, Dokumentation wiederkehrender Strukturen oder Muster, Beschreibung interner Schnittstellen, Zusammenhang von Bausteinen zu Quellcode)
o Laufzeitszenarien, insbesondere zur Erfüllung der wesentlichen Systemfunktionen, Darstellung unvollständiger Szenarien, Darstellung über verschiedene Verfeinerungsebenen
o Notationen (etwa: UML, SysML o. ä.) zur Beschreibung von Sichten
Schnittstellen beschreiben
Technische und oder übergreifende Konzepte zielgruppengerecht anfertigen
Konsistenz zwischen unterschiedlichen Bestandteilen der Architekturdokumentation prüfen bzw. herstellen
Bestandteile in Dokumenten strukturieren.
Was sollen die Teilnehmer verstehen?
Für eine nachvollziehbare Software-Architektur reicht es nicht, die Lösung zu dokumentieren. Auch architekturrelevante Anforderungen und Begründungen sind festzuhalten.
Was sollen die Teilnehmer kennen?
IEEE 1471 („Recommended Practice for Architecture Description of Software-Intensive Systems“)
Alternative Vorschläge für konkrete Sichten, zum Beispiel o Rational Unified Process (4+1)
© 2012 iSAQB e. V. V 1.6 vom 03. September 2018 Seite 11 von 16
 iSAQB-Curriculum für Advanced Level - Architekturdokumentation
 o Meta-/Sichtenmodell vom Software Engineering Institute
o arc42
• Grafische Notationen für Sichten
• FMC (Fundamental Modeling Concepts)
• RM-ODP (Reference Model of Open Distributed Processing)
// end::REMARK[]
