=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Einflussfaktoren und Randbedingungen dokumentieren

Softwarearchitekt:innen können Faktoren, die Einfluss auf Softwarearchitektur haben, identifizieren und geeignet dokumentieren.
Dazu zählen:

* Randbedingungen 
* Qualitätsanforderungen und -ziele
* Technische Risiken

[[LZ-3-2]]
==== LZ 3-2: Architekturentscheidungen dokumentieren

Softwarearchitekt:innen können Architekturentscheidungen nachvollziehbar festhalten.
Sie kennen beispielsweise _Architecture Decision Records_ als eine feste Struktur für solche Entscheidungen.


[[LZ-3-3]]
==== LZ 3-3: Architektursichten dokumentieren

Softwarearchitekt:innen können verschiedene Architektursichten angemessen einsetzen und dokumentieren.
Sie wissen, für welche Anwendungsfälle statische sowie dynamische Sichten am besten geeignet sind.
Außerdem verstehen sie, wann welcher Detailgrad sinnvoll ist.

[[LZ-3-4]]
==== LZ 3-4: Übergreifende Konzepte dokumentieren

Softwarearchitekt:innen können Konzepte, die über Modulgrenzen hinaus oder querschnittlich durch die Software gehen,
erkennen und entsprechend dokumentieren.

[[LZ-3-5]]
==== LZ 3-5: Konsistenz zwischen Teilen der Dokumentation sicherstellen

Softwarearchitekt:innen sind in der Lage, Konsistenz zwischen einzelnen Teilen der Dokumentation
herzustellen und zu bewahren.


// end::DE[]

// tag::EN[]

[[LG-3-1]]
==== LG 3-1: Document influences and constraints

Software architects can identify factors that influence software architecture and document them appropriately.
These include:

* Constraints
* Quality requirements and goals 
* Technical risks

[[LG-3-2]]
==== LG 3-2: Document architecture decisions

Software architects can record architectural decisions in a comprehensible manner.
For example, they are familiar with _Architecture Decision Records_ as a fixed structure for such decisions.


[[LG-3-3]]
==== LG 3-3: Document architectural views

Software architects can use and document different architecture views appropriately.
They know for which use cases static and dynamic views are best suited.
They also understand when which level of detail is appropriate.

[[LG-3-4]]
==== LG 3-4: Document cross-cutting concepts

Software architects can recognize concepts that go beyond module boundaries or cross-cut through the software,
and document them accordingly.

[[LG-3-5]]
==== LG 3-5: Ensure consistency between parts of the documentation

Software architects are able to establish and maintain consistency between individual parts of the documentation. 

// end::EN[]

// tag::REMARK[]
aus V 1.5

Was sollen die Teilnehmer können?
Die Architektur mittlerer bis großer IT-Systeme selbständig dokumentieren, sowohl entwicklungsbegleitend, wie bei Bedarf auch a posteriori („Nachdokumentation“).
Vorhandene Architekturdokumentation weiterentwickeln und pflegen, dabei die Qualität der Dokumentation systematisch verbessern.
Für mittlere bis große Systeme spezifisch geeignete Arten und Strukturen der Architekturdokumentation erarbeiten oder auswählen.
Faktoren, die Einfluss auf Software-Architektur haben, identifizieren und geeignet dokumentieren, z. B.
o Randbedingungen o Qualitätsziele
o Technische Risiken
Architekturentscheidungen nachvollziehbar festhalten
Unterschiedliche Sichten auf Software-Architektur mit geeigneten Beschreibungsmitteln anfertigen
o Verschiedene Aspekte von Bausteinsichten erklären und dokumentieren (Darstellung als hierarchische Verfeinerung, Dokumentation wiederkehrender Strukturen oder Muster, Beschreibung interner Schnittstellen, Zusammenhang von Bausteinen zu Quellcode)
o Laufzeitszenarien, insbesondere zur Erfüllung der wesentlichen Systemfunktionen, Darstellung unvollständiger Szenarien, Darstellung über verschiedene Verfeinerungsebenen
o Notationen (etwa: UML, SysML o. ä.) zur Beschreibung von Sichten
Schnittstellen beschreiben
Technische und oder übergreifende Konzepte zielgruppengerecht anfertigen
Konsistenz zwischen unterschiedlichen Bestandteilen der Architekturdokumentation prüfen bzw. herstellen
Bestandteile in Dokumenten strukturieren.
Was sollen die Teilnehmer verstehen?
Für eine nachvollziehbare Software-Architektur reicht es nicht, die Lösung zu dokumentieren. Auch architekturrelevante Anforderungen und Begründungen sind festzuhalten.
Was sollen die Teilnehmer kennen?
IEEE 1471 („Recommended Practice for Architecture Description of Software-Intensive Systems“)
Alternative Vorschläge für konkrete Sichten, zum Beispiel o Rational Unified Process (4+1)
© 2012 iSAQB e. V. V 1.6 vom 03. September 2018 Seite 11 von 16
 iSAQB-Curriculum für Advanced Level - Architekturdokumentation
 o Meta-/Sichtenmodell vom Software Engineering Institute
o arc42
• Grafische Notationen für Sichten
• FMC (Fundamental Modeling Concepts)
• RM-ODP (Reference Model of Open Distributed Processing)
// end::REMARK[]
