// tag::FEEDBACK[]
:filename: 01-intro/LG-1-02.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]


// tag::DE[]
[[LZ-1-2]]
==== LZ 1-2: Bedeutung von Architekturdokumentation für unterschiedliche Stakeholder verstehen

* Verstehen, dass unterschiedliche Stakeholder i.d.R. verschiedene Anforderungen an Architekturdokumentation haben, beispielsweise hinsichtlich:
** Arten von Informationen (etwa: über Schnittstellen, Bausteine, querschnittliche Themen, Entscheidungen, technische Risiken, Lösungsansätze oä)
** Darstellung solcher Informationen (als (grafische) Modelle, als reine Grafiken oder textuell)
** Detaillierungsgrad (etwa: Überblick, abstrakte oder detaillierte Darstellung)
** technische Repräsentation (mit/ohne Schreib-/Änderungsmöglichkeiten, PDF, HTML, Wiki, Textverarbeitung oä)
** Grad der Aktualität

// tag::EN[]
[[LG-1-1]]
==== LG 1-2: Understanding the Importance of Architecture Documentation for Different Stakeholders

* Understand that different stakeholders usually have different requirements for architecture documentation, for example with regard to..:
** Types of information (e.g. about interfaces, building blocks, cross-sectional topics, decisions, technical risks, approaches to solutions, etc.)
** Representation of such information (as (graphical) models, as pure graphics or textual)
** Degree of detail (e.g. overview, abstract or detailed representation)
** technical representation (with/without writing/editing options, PDF, HTML, Wiki, word processing, etc.)
** Degree of timeliness (how _up-to-date_ does documentation needs to be, up-to-the latest development/release/test version? minor/major version?)

// end::EN[]

// tag::REMARK[]

// end::REMARK[]
