=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Passende Werkzeuge für Dokumentationsarbeit auswählen

Softwarearchitekt:innen können passenden Werkzeuge für die verschiedenen Aktivitäten auswählen:

* Erstellung und Pflege von Bestandteilen von Architekturdokumentation
* Verwaltung der Bestandteile
* Kommunikation von Inhalten mit Unterstützung der Bestandteile

Sie können: 

* analoge und digitale Dokumentationswerkzeuge situations- und bedarfsgerecht einsetzen 
* eine vollständige Werkzeugkette zur Architekturdokumentation anhand konkreter Anforderungen, Randbedingungen und weiterer Einflussfaktoren nachvollziehbar auswählen.

Sie kennen jeweilige Stärken, Schwächen und typische Herausforderungen beim Einsatz und der Integration verbreiteter Werkzeugenkategorien, beispielsweise:

* Wikis
* Modellierungswerkzeuge
* Zeichenprogramme
* Textverarbeitungen
* Versionsverwaltungen
* Sonstige (etwa: Blogs, Issue-Tracker etc.)


[[LZ-4-2]]
==== LZ 4-2: Anforderungen an Dokumentationswerkzeuge und -artefakte kennen

Softwarearchitekt:innen wissen, wie Werkzeuge bei verschiedenen Aufgaben rund um Architekturdokumentation unterstützen können.

Sie wissen, dass Dokumentation:

* ähnlich wie Quellcode versioniert und Release-fähig verwaltet werden sollte
* zu jedem definierten Stand der Software herstellbar oder generierbar sein sollte

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: The is the first learning goal, in category xy
tbd.
// end::EN[]

// tag::REMARK[]
// end::REMARK[]
