=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Passende Werkzeuge für Dokumentationsarbeit auswählen

Softwarearchitekt:innen können passenden Werkzeuge für die verschiedenen Aktivitäten auswählen:

* Erstellung und Pflege von Bestandteilen von Architekturdokumentation
* Verwaltung der Bestandteile
* Kommunikation von Inhalten mit Unterstützung der Bestandteile

Sie können: 

* analoge und digitale Dokumentationswerkzeuge situations- und bedarfsgerecht einsetzen 
* eine vollständige Werkzeugkette zur Architekturdokumentation anhand konkreter Anforderungen, Randbedingungen und weiterer Einflussfaktoren nachvollziehbar auswählen.

Sie kennen jeweilige Stärken, Schwächen und typische Herausforderungen beim Einsatz und der Integration verbreiteter Werkzeugenkategorien, beispielsweise:

* Wikis
* Modellierungswerkzeuge
* Zeichenprogramme
* Textverarbeitungen
* Versionsverwaltungen
* Sonstige (etwa: Blogs, Issue-Tracker etc.)


[[LZ-4-2]]
==== LZ 4-2: Anforderungen an Dokumentationswerkzeuge und -artefakte kennen

Softwarearchitekt:innen wissen, wie Werkzeuge bei verschiedenen Aufgaben rund um Architekturdokumentation unterstützen können.

Sie wissen, dass Dokumentation:

* ähnlich wie Quellcode versioniert und Release-fähig verwaltet werden sollte
* zu jedem definierten Stand der Software herstellbar oder generierbar sein sollte

// end::DE[]

// tag::EN[]

[[LZ-4-1]]
==== LZ 4-1: Select appropriate tools for documentation work

Software architects can select appropriate tools for different activities:

* Creation and maintenance of parts of architectural documentation
* Parts management
* Communication of content with the support of the parts

They are able to: 

* use analog and digital documentation tools according to the situation and requirements.
* comprehensibly select a complete tool chain for architecture documentation based on concrete requirements, constraints and other influences.

They are aware of respective strengths, weaknesses and typical challenges when using and integrating common tool categories, for example:

* Wikis
* Modeling tools
* Drawing software
* Word processors
* Version control systems
* Other (such as: blogs, issue trackers, etc.)


[[LZ-4-2]]
==== LZ 4-2: Know requirements for documentation tools and artifacts

Software architects know how tools can support them in various activities related to architecture documentation.

They know that documentation:

* should be managed in a versioned and release-ready manner similar to source code.
* should be producible or generatable for every defined state of the software.

// end::EN[]

// tag::REMARK[]
// end::REMARK[]
