=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Passende Werkzeuge für Dokumentationsarbeit auswählen

Softwarearchitekt:innen können passenden Werkzeuge für die verschiedenen Aktivitäten auswählen:

* Erstellung und Pflege von Bestandteilen von Architekturdokumentation
* Verwaltung der Bestandteile
* Kommunikation von Inhalten mit Unterstützung der Bestandteile

Sie können:

* analoge und digitale Dokumentationswerkzeuge situations- und bedarfsgerecht einsetzen
* eine vollständige Werkzeugkette zur Architekturdokumentation anhand konkreter Anforderungen, Randbedingungen und weiterer Einflussfaktoren nachvollziehbar auswählen.

Sie kennen jeweilige Stärken, Schwächen und typische Herausforderungen beim Einsatz und der Integration verbreiteter Werkzeugenkategorien, beispielsweise:

* Wikis
* Modellierungswerkzeuge
* Zeichenprogramme
* Textverarbeitungen
* Versionsverwaltungen
* Sonstige (etwa: Blogs, Issue-Tracker etc.)


[[LZ-4-2]]
==== LZ 4-2: Anforderungen an Dokumentationswerkzeuge und -artefakte kennen

Softwarearchitekt:innen wissen, wie Werkzeuge bei verschiedenen Aufgaben rund um Architekturdokumentation unterstützen können.

Sie wissen, dass Dokumentation:

* ähnlich wie Quellcode versioniert und Release-fähig verwaltet werden sollte
* zu jedem definierten Stand der Software herstellbar oder generierbar sein sollte

[[LZ-4-3]]
==== LZ 4-3: Docs-As-Code Ansatz kennen

Softwarearchitekt:innen kennen den Ansatz _Documentation-As-Code_, bei dem die Architekturdokumentation ganz oder teilweise aus quellcode-ähnlichen Artefakten (z.B. Markdown oder AsciiDoc) erzeugt wird.

Sie kennen Werkzeuge, mit denen auch grafische Darstellungen aus textuellen Beschreibungen erzeugt werden können (etwa: <<plantuml>>)

[[LZ-4-4]]
==== LZ 4-4: GenAI-Werkzeuge als Unterstützung für Architekturdokumentation anwenden

Softwarearchitekt:innen kennen die Chancen und Risiken beim Einsatz von Generative AI (GenAI)-Werkzeugen im Rahmen der Dokumentation. 
Sie können solche Werkzeuge gezielt für einzelne Teilbereiche (etwa: architekturrelevante Anforderungen, Lösungsbeschreibung, Bewertung der Dokumentation) anwenden und sind in der Lage, die Ergebnisse abzusichern.


// end::DE[]

// tag::EN[]

[[LG-4-1]]
==== LG 4-1: Select appropriate tools for documentation work
// existing title meets standards - checked 2025.10.13 and Gemini-2.5-Pro

Software architects can select appropriate tools for different activities:

* Creation and maintenance of parts of architectural documentation
* Parts management
* Communication of content with the support of the parts

They are able to:

* use analog and digital documentation tools according to the situation and requirements.
* comprehensibly select a complete tool chain for architecture documentation based on concrete requirements, constraints and other influences.

They are aware of respective strengths, weaknesses and typical challenges when using and integrating common tool categories, for example:

* Wikis
* Modeling tools
* Drawing software
* Word processors
* Version control systems
* Other (such as: blogs, issue trackers, etc.)


[[LG-4-2]]
==== LG 4-2: Know requirements for documentation tools and artifacts
// LG-title-proposal: Define requirements for documentation tools and artifacts
// LG-title-proposal: Elicit requirements for the documentation toolchain

Software architects know how tools can support them in various activities related to architecture documentation.

They know that documentation:

* should be managed in a versioned and release-ready manner similar to source code.
* should be producible or generatable for every defined state of the software.


[[LG-4-3]]
==== LG 4-3: Docs-As-Code Approach
// LG-title-proposal: Apply the docs-as-code approach for documentation
// LG-title-proposal: Use docs-as-code to manage documentation artifacts

Software architects are familiar with the Documentation-As-Code approach, where architectural documentation is generated in whole or in part from source code-like artifacts (e.g.  Markdown or AsciiDoc).

They are familiar with tools that can also be used to generate graphical representations from textual descriptions (e.g. <<plantuml>>).


[[LG-4-4]]
==== LG 4-4: Using GenAI tools to support architecture documentation
// LG-title-proposal: Apply GenAI tools to support architecture documentation
// LG-title-proposal: Use GenAI tools for creating and maintaining documentation

Software architects are aware of the opportunities and risks involved in using generative AI (GenAI) tools for documentation purposes. 
They can apply these tools in a targeted manner for individual sub-areas (e.g., architecture-related requirements, solution description, evaluation of documentation) and are able to validate the results.


// end::EN[]


