// (c) iSAQB e.V. (https://isaqb.org)
// ====================================================

// tag::FEEDBACK[]
:filename: 42-glossary/00-glossary.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::REMARK[]
[NOTE]
====
* GS, Oct. 2019: The glossary is currently maintained in EN (English) only.
* For an example for cross-references within the glossary, see  "Gherkin".
We don't currently use AsciiDoc cross-references, but stick to "->" symbols instead.
====
// end::REMARK[]

// tag::DE[]
// end::DE[]

// tag::EN[]
[glossary]
== Glossary

[glossary]

arc42:: An open-source _template_ for software architecture documentation. Available in numerous formats, extensively documented, many examples available. See https://arc42.org (overview and downloads) and https://docs.arc42.org (documentation and more than 130 tipps for effective usage)

ASR:: _Architecturally Significant Requirements_ are those requirements that especially shape or influence architectural decisions.

Gherkin:: Domain-specific language for writing ->BDD scenarios in ->GWT syntax.


// end::EN[]
