=== {learning-goals}

// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Notwendigkeit der Überprüfung auf Gebrauchstauglichkeit erkennen

Softwarearchitekt:innen erkennen die Überprüfung auf Gebrauchstauglichkeit als einen wesentlichen Erfolgsfaktor der Dokumentation.

[[LZ-5-2]]
==== LZ 5-2: Verschiedene Arten der Begutachtung differenzieren

Softwarearchitekt:innen können zwischen inhaltlicher und formaler Begutachtung einer Architekturdokumentation differenzieren.


[[LZ-5-3]]
==== LZ 5-3: Review von Architektur und Dokumentation differenzieren

Softwarearchitekt:innen können Review/Begutachtung einer Dokumentation von der Bewertung der Architektur oder des Systems abgrenzen.


[[LZ-5-4]]
==== LZ 5-4:  Ziele von Dokumentations-Reviews ermitteln und erklären

Softwarearchitekt:innen können mit den betroffenen Personen ("Stakeholdern") mögliche Ziele von Dokumentations-Reviews ermitteln und diese Ziele anderen Personen erklären.

[[LZ-5-5]]
==== LZ 5-5: Checklisten und Fragenkataloge für Reviews erstellen

Softwarearchitekt:innen können Checklisten und Fragenkataloge für Reviews von Dokumentation erstellen.

[[LZ-5-6]]
==== LZ 5-6: Verschiedene Rollen bei Dokumentations-Reviews ausüben können

Softwarearchitekt:innen können im Rahmen von Dokumentations-Reviews in der Rolle von

* Autor:innen mit Einwänden angemessen umgehen,
* Gutachter:innen konstruktive Rückmeldungen an Autor:innen geben,
* Moderator:innen ein fachliches Review leiten.

[[LZ-5-7]]
==== LZ 5-7: Auf Basis von Review-Ergebnissen die Qualität von Dokumentation verbessern

Softwarearchitekt:innen können auf Basis ermittelter Review-Ergebnisse vorhandene Architekturdokumentation weiterentwickeln und pflegen und dabei die Qualität dieser Dokumentation systematisch verbessern.

// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Recognize the need to check for fitness for purpose

Software architects recognize checking for fitness for purpose as a key success factor of documentation.

[[LG-5-2]]
==== LG 5-2: Differentiate different types of assessment

Software architects can differentiate between content and formal assessment of architectural documentation.


[[LG-5-3]]
==== LG 5-3: Differentiate review from architecture and documentation

Software architects can distinguish reviewing documentation from evaluating the architecture or the system.

[[LG-5-4]]
==== LG 5-4:  Identify and explain goals of documentation reviews

Software architects can identify possible goals of documentation reviews with the concerned persons ("stakeholders") and explain these goals to other persons.
[[LG-5-5]]
==== LG 5-5: Create checklists and questionnaires for reviews

Software architects can create checklists and questionnaires for documentation reviews.

[[LG-5-6]]
==== LG 5-6: Be able to perform different roles in documentation reviews

Software architects can take on the following roles in the context of documentation reviews

* Deal with objections appropriately as an author,
* Provide constructive feedback to authors as reviewers,
* Lead a subject matter review as a facilitator.

[[LG-5-7]]
==== LG 5-7: Improve the quality of documentation based on review results

Software architects can use review results to further develop and maintain existing architecture documentation and systematically improve the quality of this documentation.

// end::EN[]


