=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Architekturdokumentation erstellen

Softwarearchitekt:innen können angemessene Architekturdokumentation für mittlere bis große IT-Systeme in beispielsweise folgenden Situationen erstellen:

* Erstellung neuer Systeme
* Weiterentwicklung bestehender Systeme mit vorhandener Dokumentation
* Nachdokumentation bestehender Systeme ohne vorhandene Dokumentation
* Dokumentation in Ausnahmesituationen (wenig Budget, wenig Zeit, wenig verfügbare Informationsquellen etc.)

Sie können Zielgruppen und Ziele der Dokumentation ermitteln (siehe <<LZ-2-2, LZ 2-2>>).

Details zu den notwendigen methodischen Mitteln finden sich in den Lernzielen <<LZ-3-1,LZ 3-1>> bis <<LZ-3-5, LZ 3-5>>.

[[LZ-2-2]]
==== LZ 2-2: Zielgruppen und Ziele der Architekturdokumentation ermitteln

Softwarearchitekt:innen können die Zielgruppen („Stakeholder“) für Architekturdokumentation ermitteln
(beispielsweise Management, Entwicklungsteam, fachliche Stakeholder, betriebliche Stakeholder, Test/QS).

Sie können zusammen mit diesen Stakeholdern konkrete Ziele der Dokumentation ermitteln.


[[LZ-2-3]]
==== LZ 2-3: Situativ passende Struktur einer Architekturdokumentation bestimmen

Softwarearchitekt:innen können für gegebene Situationen und Systeme eine passende Struktur für die Architekturdokumentation auswählen oder erarbeiten.

Als Basis dafür dienen Zielgruppen und Ziele (siehe <<LZ-2-2, LZ 2-2>>) sowie Templates (siehe <<LZ-2-5, LZ 2-5>>).

[[LZ-2-4]]
==== LZ 2-4: Situativ passendes Vorgehen zur Architekturdokumentation bestimmen

Softwarearchitekt:innen finden für gegebene Situationen ein passendes Vorgehen zur Dokumentation.
Sie können Stakeholdern und dem Entwicklungsteam die Vor- und Nachteile verschiedener Ansätze erläutern, etwa:

* Dokumentation entsteht **begleitend zur** Entwicklungsarbeit
* Dokumentation entsteht **vor** der Entwicklung/Implementierung
* Dokumentation entsteht **nach** der Entwicklung („Dokumentations-Sprint“)
* Dokumentation wird durch Personen **aus dem Entwicklungsteam** erstellt und gepflegt
* Dokumentation wird durch Personen **außerhalb des Entwicklungsteams** erstellt und gepflegt

Sie wissen, dass agile Entwicklung und Architekturdokumentation nicht im Widerspruch zueinander stehen, und können dies Stakeholdern gegenüber begründen.


[[LZ-2-5]]
==== LZ 2-5: Beispiele standardisierter Dokumentationsstrukturen (Templates) kennen

Softwarearchitekt:innen kennen Beispiele von Architekturtemplates, etwa:

* arc42
* C4 (Simon Brown)
* IEEE 1471 („Recommended Practice for Architecture Description of Software-Intensive Systems“)

// end::DE[]


// tag::EN[]

[[LG-2-1]]
==== LG 2-1: Create architecture documentation

Software architects can create appropriate architecture documentation for medium to large IT systems in situations such as the following:

* Building new systems
* Ongoing development of existing systems with existing documentation
* Post-documentation of already existing systems without available documentation
* Documentation in extraordinary situations (little budget, little time, few available sources of information, etc.)

They can identify target groups and goals of the documentation (see <<LG-2-2, LG 2-2>>).

Details on the necessary methods can be found in the learning goals <<LG-3-1,LG 3-1>> to <<LG-3-5, LG 3-5>>.

[[LG-2-2]]
==== LG 2-2: Identify target audiences and goals of architectural documentation

Software architects can identify the target audiences ("stakeholders") for architecture documentation
(e.g. management, development team, business stakeholders, operations stakeholders, test/QA).

They can work together with these stakeholders to identify specific goals for the documentation.

[[LG-2-3]]
==== LG 2-3: Determine the appropriate structure of architecture documentation for a given situation

Software architects are able to select or develop a suitable structure for architecture documentation for given situations and systems.

Target audiences and goals (see <<LG-2-2, LG 2-2>>) and templates (see <<LG-2-5, LG 2-5>>) serve as the basis for this.

[[LG-2-4]]
==== LG 2-4: Determine the appropriate architecture documentation procedures for each situation

Software architects find a suitable documentation procedures for given situations.
They can explain the advantages and disadvantages of different approaches to stakeholders and the development team, such as:

* Documentation is created **alongside** development work
* Documentation is created **before** development/implementation
* Documentation is created **after** development ("documentation sprint")
* Documentation is created and maintained by people **from the development team**.
* Documentation is created and maintained by people **outside the development team**.

They know that agile development and architecture documentation are not in conflict and can justify this to stakeholders.

[[LG-2-5]]
==== LG 2-5: Know examples of standardized documentation structures (templates)

Software architects know examples of architecture templates, such as:

* arc42
* C4 (Simon Brown)
* IEEE 1471 („Recommended Practice for Architecture Description of Software-Intensive Systems“)

// end::EN[]

