
// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1: Architekturdokumentation erstellen 

Softwarearchitekt:innen können angemessene Architekturdokumentation für mittlere bis große IT-Systeme in beispielsweise folgenden Situationen erstellen:

* Erstellung neuer Systeme
* Weiterentwicklung bestehender Systeme mit vorhandener Dokumentation
* Nachdokumentation bestehender Systeme ohne vorhandene Dokumentation
* Dokumentation in Ausnahmesituationen (wenig Budget, wenig Zeit, wenig verfügbare Informationsquellen etc.)

Sie können Zielgruppen und Ziele der Dokumentation ermitteln (siehe <<LZ-2-2, LZ 2-2>>).

Details zu den notwendigen methodischen Mitteln finden sich in den Lernzielen <<LZ-3-1,LZ 3-1>> bis <<LZ-3-5, LZ 3-5>>.

[[LZ-2-2]]
==== LZ 2-2: Zielgruppen und Ziele der Architekturdokumentation ermitteln

Softwarearchitekt:innen können die Zielgruppen („Stakeholder“) für Architekturdokumentation ermitteln
(beispielsweise Management, Entwicklungsteam, fachliche Stakeholder, betriebliche Stakeholder, Test/QS).

Sie können zusammen mit diesen Stakeholdern konkrete Ziele der Dokumentation ermitteln.


[[LZ-2-3]]
==== LZ 2-3: Situativ passende Struktur einer Architekturdokumentation bestimmen

Softwarearchitekt:innen können für gegebene Situationen und Systeme eine passende Struktur für die Architekturdokumentation auswählen oder erarbeiten.

Als Basis dafür dienen Zielgruppen und Ziele (siehe <<LZ-2-2, LZ 2-2>>) sowie Templates (siehe <<LZ-2-5, LZ 2-5>>).

[[LZ-2-4]]
==== LZ 2-4: Situativ passendes Vorgehen zur Architekturdokumentation bestimmen

Softwarearchitekt:innen finden für gegebene Situationen ein passendes Vorgehen zur Dokumentation.
Sie können Stakeholdern und dem Entwicklungsteam die Vor- und Nachteile verschiedener Ansätze erläutern, etwa:

* Dokumentation entsteht **begleitend zur** Entwicklungsarbeit
* Dokumentation entsteht **vor** der Entwicklung/Implementierung
* Dokumentation entsteht **nach** der Entwicklung („Dokumentations-Sprint“)
* Dokumentation wird durch Personen **aus dem Entwicklungsteam** erstellt und gepflegt
* Dokumentation wird durch Personen **außerhalb des Entwicklungsteams** erstellt und gepflegt

Sie wissen, dass agile Entwicklung und Architekturdokumentation nicht im Widerspruch zueinander stehen, und können dies Stakeholdern gegenüber begründen.


[[LZ-2-5]]
==== LZ 2-5: Beispiele standardisierter Dokumentationsstrukturen (Templates) kennen

Softwarearchitekt:innen kennen Beispiele von Architekturtemplates, etwa:

* arc42
* C4 (Simon Brown)
* IEEE 1471 („Recommended Practice for Architecture Description of Software-Intensive Systems“)

// end::DE[]


// tag::EN[]
[[LG-2-1]]
==== LG 2-1: TBD
tbd.
// end::EN[]

// tag::REMARK[]
Aus Version 1.5 (Verweise auf LZ nachträglich eingefügt):

Teilnehmende können für gegebene Situation angemessene Vorgehensweise für die Dokumentation bestimmen/entwerfen.

==== 4.2.1 Was sollen die Teilnehmer können?

* Architekturdokumentation für folgende Situationen erstellen (siehe <<LZ-2-1>>):
** Erstellung neuer Systeme
** Weiterentwicklung bestehender Systeme mit vorhandener Dokumentation
** Nachdokumentation bestehender Systeme ohne vorhandene Dokumentation
** Dokumentation in Ausnahmesituationen (wenig Budget, wenig Zeit, wenig verfügbare Informationsquellen etc.)
* Zielgruppen und Ziele der Dokumentation ermitteln (siehe <<LZ-2-2>>)
* Zu erstellende Bestandteile bedarfsgerecht auswählen
* Die Vorteile fester Gliederungen und Strukturen für (technische) Dokumentation argumentieren können. (siehe <<LZ-2-3>>)

==== 4.2.2 Was sollen die Teilnehmer verstehen?
* Dokumentation entsteht im Idealfall begleitend zu Architektur und Entwicklung, nicht hinterher.
* Agilität und Dokumentation stehen nicht im Widerspruch zueinander.

==== 4.2.3 Was sollen die Teilnehmer kennen?
* Die Rolle von Architekturdokumentation in verschiedenen konkreten Vorgehensmodellen
* Verschiedene Vorschläge und Vorlagen für Standardgliederungen (z. B. arc42, SEI).
// end::REMARK[]

