=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Nutzen und Ziele von Architekturdokumentation verstehen

Softwarearchitekt:innen wissen, dass Architekturdokumentation kein Selbstzweck ist.

Sie können den Nutzen und verschiedene Ziele von Architekturdokumentation erklären, beispielsweise:

* Architekturdokumentation unterstützt beim Lösungsentwurf, und bei der Kommunikation der Lösung dem Team und anderen (z. B. Auftraggebern) gegenüber.
* Unterstützung der Entwicklung durch Vermittlung architektur- und entwicklungsrelevanter Entscheidungen, Fakten und Gründe.
* Schriftliche Kommunikation relevanter struktureller und konzeptioneller Sachverhalte
* Konservierung von Wissen über Entwicklung und Architektur

Sie können diese Ziele und den Nutzen von Dokumentation gegenüber Stakeholdern überzeugend vertreten.

[[LZ-1-2]]
==== LZ 1-2: Bedeutung von Architekturdokumentation für unterschiedliche Stakeholder verstehen

Softwarearchitekt:innen verstehen, dass unterschiedliche Stakeholder i. d. R. verschiedene Anforderungen an Architekturdokumentation haben, beispielsweise hinsichtlich:

* Arten von Informationen, etwa zu Schnittstellen, Bausteinen, querschnittlichen Themen, Entscheidungen, technischen Risiken, grundlegenden Lösungsansätzen o. ä.
* Darstellung solcher Informationen, etwa als (grafische oder textuelle) Modelle, als Grafiken oder Text
* Detaillierungsgrad, etwa: Überblick, abstrakte oder detaillierte Darstellung
* technische Repräsentation etwa mit oder ohne Schreib-/Änderungsmöglichkeiten, als PDF, HTML, Wiki, Textverarbeitung o. ä.
* Grad der Aktualität.

[[LZ-1-3]]
==== LZ 1-3: Architekturdokumentation gegen andere Arten von Dokumentation abgrenzen

Softwarearchitekt:innen verstehen, dass Architekturdokumentation Berührungspunkte und teilweise Überdeckung zu anderen Arten von Dokumentation besitzt, beispielsweise:

* Anforderungs-/Requirements-Dokumentation
* Implementierungsdokumentation
* Managementdokumentation
* Testdokumentation
* Betriebsdokumentation

[[LZ-1-4]]
==== LZ 1-4: Typische Notations- und Darstellungsmittel für Architekturdokumentation kennen

Softwarearchitekt:innen kennen verschiedene Notations- und Darstellungsmittel für Architekturinformationen, beispielsweise:

* Modellierungsmethoden, wie UML, C4 (<<brown-c4>>), ArchiMate, Business-Process Modeling Notation (BPMN), Entity-Relationship (ER) Diagramme, Ereignis-Prozess-Ketten (EPK)
* Textuelle Erläuterungen von Entscheidungen
* Canvas (e.g. Architecture-Communication-Canvas <<acc>> oder Bounded-Context-Canvas <<bcc>>)

Sie wissen, dass formalere Notationen wie UML für Architekturdokumentation hilfreich sein können, aber nicht zwingend erforderlich sind.

[[LZ-1-5]]
==== LZ 1-5: Varianten von Entwicklungsvorgehen und deren Einfluss auf Architekturdokumentation kennen

Softwarearchitekt:innen wissen, dass

* in eher formalen Entwicklungsvorhaben (etwa _safety-critical_) hohe Ansprüche an Architekturdokumentation gelten
* in eher leichtgewichtigen Entwicklungsprozessen (agilen Prozesse) Teams eine dem System und dessen Umfeld angemessene Art von Dokumentation wählen sollten
* je nach Vorgehen und Rahmenbedingungen des Vorhabens sehr unterschiedliche Dokumentationsarbeiten zu leisten sind

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understand the benefits and goals of architecture documentation
// LG-title-proposal: Explain the benefits and goals of architecture documentation

Software architects understand that architecture documentation is not an end in itself.

They can explain the benefits and various goals of architectural documentation, such as:

* Architecture documentation supports solution design, and communication of the solution to the team and others (e.g., clients)
* Support implementation by communicating architectural and development decisions, facts, and rationale
* Written communication of relevant structural and conceptual topics
* Preservation of knowledge about development and architecture

They can advocate these goals and the benefits of documentation to stakeholders in a convincing manner.

[[LG-1-2]]
==== LG 1-2: Understand the importance of architecture documentation for different stakeholders
// LG-title-proposal: Adapt architecture documentation for different stakeholders
// LG-title-proposal: Tailor architecture documentation to stakeholder needs

Software architects understand that different stakeholders usually have different requirements for architecture documentation, for example with regard to..:

* Types of information (e.g. about interfaces, building blocks, cross-sectional topics, decisions, technical risks, approaches to solutions, etc.)
* Representation of such information (as (graphical) models, as pure graphics or textual)
* Degree of detail (e.g. overview, abstract or detailed representation)
* technical representation (with/without writing/editing options, PDF, HTML, Wiki, word processing, etc.)
* Degree of timeliness (how _up-to-date_ does documentation needs to be, up-to-the latest development/release/test version? minor/major version?)

[[LG-1-3]]
==== LG 1-3: Differentiate architectural documentation from other types of documentation
// existing title meets standards - checked 2025.10.13 and Gemini-2.5-Pro

Software architects understand that architecture documentation has points of contact and partial overlap with other types of documentation, for example:

* Requirements documentation
* Implementation documentation
* Management documentation
* Test documentation
* Operations documentation

[[LG-1-4]]
==== LG 1-4: Know typical notation and representation methods for architectural documentation
// LG-title-proposal: Select appropriate notations for architecture documentation
// LG-title-proposal: Choose suitable representation methods for architecture documentation

Software architects are familiar with various methods of notation and representation of architectural information, for example:

* Modeling methods, such as UML, C4 (<<brown-c4>>), ArchiMate, Business-Process Modeling Notation (BPMN), Entity-Relationship (ER) diagrams, Event-driven process chains (EPC)
* Textual explanations of decisions
* Canvas (e.g. Architecture Communication Canvas <<acc>> or Bounded Context Canvas <<bcc>>)

They know that more formal notations such as UML can be helpful for architecture documentation, but are not mandatory.

[[LG-1-5]]
==== LG 1-5: Know variants of development processes and their influence on architecture documentation
// LG-title-proposal: Adapt documentation efforts to different development processes

Software architects know that

* in more formal development projects (e.g. _safety-critical_) high demands on architecture documentation apply.
* in more lightweight development processes (agile processes) teams should choose a type of documentation appropriate to the system and its environment.
* depending on the process and the constraints of the project, very different documentation work has to be carried out.

// end::EN[]



