

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Nutzen und Ziele von Architekturdokumentation verstehen

Softwarearchitekt:innen wissen, dass Architekturdokumentation kein Selbstzweck ist.

Sie können den Nutzen und verschiedene Ziele von Architekturdokumentation erklären, beispielsweise: 

* Architekturdokumentation unterstützt beim Lösungsentwurf, und bei der Kommunikation der Lösung dem Team und anderen (z. B. Auftraggebern) gegenüber.
* Unterstützung der Entwicklung durch Vermittlung architektur- und entwicklungsrelevanter Entscheidungen, Fakten und Gründe.
* Schriftliche Kommunikation relevanter struktureller und konzeptioneller Sachverhalte
* Konservierung von Wissen über Entwicklung und Architektur

Sie können diese Ziele und den Nutzen von Dokumentation gegenüber Stakeholdern überzeugend vertreten.

[[LZ-1-2]]
==== LZ 1-2: Bedeutung von Architekturdokumentation für unterschiedliche Stakeholder verstehen

Softwarearchitekt:innen verstehen, dass unterschiedliche Stakeholder i.d.R. verschiedene Anforderungen an Architekturdokumentation haben, beispielsweise hinsichtlich:

* Arten von Informationen, etwa zu Schnittstellen, Bausteinen, querschnittlichen Themen, Entscheidungen, technischen Risiken, grundlegenden Lösungsansätzen oä
* Darstellung solcher Informationen, etwa als (grafische oder textuelle) Modelle, als Grafiken oder Text
* Detaillierungsgrad, etwa: Überblick, abstrakte oder detaillierte Darstellung
* technische Repräsentationm etwa mit oder ohne Schreib-/Änderungsmöglichkeiten, als PDF, HTML, Wiki, Textverarbeitung oä
* Grad der Aktualität

[[LZ-1-3]]
==== LZ 1-3: Architekturdokumentation gegen andere Arten von Dokumentation abgrenzen

Softwarearchitekt:innen verstehen, dass Architekturdokumentation Berührungspunkte und teilweise Überdeckung zu anderen Arten vo Dokumentation besitzt, beispielsweise:

* Anforderungs-/Requirements-Dokumentation
* Implementierungsdokumentation
* Managementdokumentation
* Testdokumentation
* Betriebsdokumentation

[[LZ-1-4]]
==== LZ 1-4: Typische Notations- und Darstellungsmittel für Architekturdokumentation kennen

Softwarearchitekt:innen kennen verschiedene Notations- und Darstellungsmittel für Architekturinformationen kennen, beispielsweise:

* Modellierungsmethoden, beispielsweise UML, BPMN, ER-Diagramme, Ereignis-Prozessketten
* Textuelle Erläuterungen von Entscheidungen

Sie wissen, dass formalere Notationen wie UML für Architekturdokumentation hilfreich sein können, aber nicht zwingend erforderlich sind.

[[LZ-1-5]]
==== LZ 1-5: Varianten von Entwicklungsvorgehen und deren Einfluss auf Architekturdokumentation kennen

Softwarearchitekt:innen wissen, dass

* in eher formalen Entwicklungsvorhaben (etwa _safety-critical_) hohe Ansprüche an Architekturdokumentation gelten
* in eher leichtgewichtigen Entwicklungsprozessen (agilen Prozesse) Teams eine dem System und dessen Umfeld angemessene Art von Dokumentation wählen sollten
* je nach Vorgehen und Rahmenbedingungen des Vorhabens sehr unterschiedliche Dokumentationsarbeiten zu leisten sind

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: The is the first learning goal, in category xy
tbd.

[[LG-1-2]]
==== LG 1-2: Understanding the Importance of Architecture Documentation for Different Stakeholders

* Understand that different stakeholders usually have different requirements for architecture documentation, for example with regard to..:
** Types of information (e.g. about interfaces, building blocks, cross-sectional topics, decisions, technical risks, approaches to solutions, etc.)
** Representation of such information (as (graphical) models, as pure graphics or textual)
** Degree of detail (e.g. overview, abstract or detailed representation)
** technical representation (with/without writing/editing options, PDF, HTML, Wiki, word processing, etc.)
** Degree of timeliness (how _up-to-date_ does documentation needs to be, up-to-the latest development/release/test version? minor/major version?)
// end::EN[]


// tag::REMARK[]

// end::REMARK[]
