// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

{curriculum-short} vermittelt die Fähigkeiten:

* die Dokumentation von Softwarearchitekturen selbständig zu konzipieren und zu erstellen 
* bestehende Dokumentation bezüglich ihrer Eignung und Angemessenheit zu bewerten 
* bestehende Dokumentation zu verbessern.

Teilnehmende lernen, die wesentlichen Aspekte von Softwarearchitekturen (u. a. Entscheidungen, Strukturen, Konzepte, Qualitätsanforderungen und Sichten) systematisch zu beschreiben.
Dazu stellt {curriculum-short} grundlegende Beschreibungs- und Notationsmittel sowie mögliche Werkzeuge zur praktischen Umsetzung vor.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

{curriculum-short} teaches the skills to:

* independently design and create software architecture documentation.
* evaluate existing documentation for suitability and adequacy. 
* improve existing documentation.

Participants learn to systematically describe the essential aspects of software architectures (including decisions, structures, concepts, quality requirements and views).
For this purpose, {curriculum-short} introduces basic description and notation methods as well as possible tools for practical implementation.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Hier bitte das Modul bzw. dessen Lerninhalte zusammenfassend in 5-8 Sätzen beschreiben. Dabei `{curriculum-name}`
nicht entfernen, beim Zusammenbauen wird dieser Platzhalter mit dem Modulnamen ersetzt.
====
// end::REMARK[]
