// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

ADOC vermittelt die Fähigkeiten:

* die Dokumentation von Softwarearchitekturen selbständig zu konzipieren und zu erstellen 
* bestehende Dokumentation bezüglich ihrer Eignung und Angemessenheit zu bewerten 
* bestehende Dokumentation zu verbessern.

Teilnehmende lernen, die wesentlichen Aspekte von Softwarearchitekturen (u.a. Entscheidungen, Strukturen, Konzepte, Qualitätsanforderungen und Sichten) systematisch zu beschreiben.
Dazu stellt ADOC grundlegende Beschreibungs- und Notationsmittel sowie mögliche Werkzeuge zur praktischen Umsetzung vor.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module presents {curriculum-short} to the participants …
At the end of the module, the participants know … and are able to …
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Hier bitte das Modul bzw. dessen Lerninhalte zusammenfassend in 5-8 Sätzen beschreiben. Dabei `{curriculum-name}`
nicht entfernen, beim Zusammenbauen wird dieser Platzhalter mit dem Modulnamen ersetzt.
====
// end::REMARK[]
