
// tag::DE[]
=== Voraussetzungen

Teilnehmende sollten folgende Kenntnisse und/oder Erfahrung mitbringen:

* Grundlagen der Beschreibung von Architekturen mit Hilfe verschiedener Sichten, übergreifender Konzepte, Entwurfsentscheidungen, Randbedingungen etc., wie es im CPSA- F Foundation Level vermittelt wird.
* Wünschenswert sind eigene Erfahrungen in der Erstellung und Pflege technischer Dokumentation von Software, insbesondere der Architektur von Software- oder Software-nahen Systemen.


Hilfreich für das Verständnis einiger Konzepte sind darüber hinaus:

* Kenntnis typischer Herausforderungen bei Erstellung und Pflege von technischer
Dokumentation:
** Auswahl geeigneter Dokumentationsstrukturen, Notationen, Ergebnistypen (Stakeholderorientierung)
** Behandlung großer Dokumentationen (insbesondere vorhandener oder veralteter Dokumentation)
** Auswahl, Konfiguration und Einführung von Werkzeugketten (mit welchen Mitteln kann Dokumentation angemessen erstellt und gepflegt werden),
** Versionierung von Dokumenten (Modelle und Texte)
** Dokumentation in Teams, arbeitsteilige Erstellung und Pflege
** Inhaltsbezogene und formale Reviews von Dokumentation.

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants should have the following knowledge and/or experience:

* Fundamentals of describing architectures using different views, crosscutting concepts, design decisions, constraints, etc., as taught in CPSA- F Foundation Level.
* Own experience in the creation and maintenance of technical documentation of software, especially the architecture of software or software-related systems is desirable.

Helpful for the understanding of some concepts are furthermore:

* Knowledge of typical challenges in creating and maintaining technical
documentation:
** Selection of appropriate documentation structures, notations, deliverable types (stakeholder orientation)
** Handling of large documentation (especially existing or obsolete documentation)
** Selection, configuration and implementation of tool chains (by what means can documentation be adequately created and maintained),
** Versioning of documents (models and texts)
** Documentation in teams, creation and maintenance based on work distribution
** Content-based and formal reviews of documentation.

// end::EN[]

// tag::REMARK[]

// end::REMARK[]
